 <!doctype html>
<html lang="en">
<head>
<jsp:include page="head.jsp" flush="true" />
<title>InSighter</title>
<link rel="stylesheet" href="/Gitmining/assets/css/set.css" />
<style type="text/css">
h1>p {
	transition: all 2s;
	-moz-transition: all 2s;
	webkit-transition: all 2s;
	o-transition: all 2s;
	font-size: 0.5em;
	margin: 20px 0 0;
}

h1:hover>p {
	font-size: 0.6em;
}
</style>
</head>
<body>
	<div class="wrapper">
		<jsp:include page="sidebar.jsp" flush="true" />

		<div class="main-panel">
			<jsp:include page="topbar.jsp" flush="true" />
			
			<div class="landing-header">
				<figure class="effect-oscar">
					<figcaption>
						<h2>INSIGHTER</h2>
						<p>Programming is the art arisen from life<br />In this gallery<br />
							Each code is a masterpiece<br />The further you insight<br />
							The deeper you wallow</p>
					</figcaption>			
				</figure>
			</div>

			<div class="section landing-section">
				<div class="container" style="width: 90%;">
					<h2 style="text-align: center; margin-bottom: 0.5em;">About Project</h2>
					<div class="col-md-12">
						<ul>
							<li>
								<h5>The website is seamlessly linked with Github, which is accessible by <b>right clicking</b> any repository name.</h5>
							</li>
							<li>
								<h5>Recommend repositories are generated by machine learning professional. If you have any doubts, click <b>"potential relevant"</b> under recommend cards to browse the analysis procedure roughly.</h5>
							</li>
							<li>
								<h5>It's highly recommended that you sign in as a user to gain the best experience. We will provide you with a detailed learning schedule. You can register with your <b>Github</b> account. On your first register, please set your basic information on the welcome page.</h5>
							</li>
							<li>
								<h5>This is an open source project, click <a href="http://114.55.35.12/141250016_cseiii_GitMining/InSighter" target="_blank"><b>here</b></a> to browse the developing information on GitLab. It's our pleasure if you make any suggestion.</h5>
							</li>
						</ul>
					</div>
				</div>
			</div>

			<div class="section section-light-brown text-center landing-section">
				<div class="container" style="width: 90%;">
					<h2>About Us</h2>
					<div class="col-md-3">
						<div class="team-player">
							<img src="/Gitmining/images/czw.jpg" alt="Thumbnail Image"
								class="img-circle img-responsive">
							<h5>Chen Zhiwei</h5>
						</div>
					</div>
					<div class="col-md-3">
						<div class="team-player">
							<img src="/Gitmining/images/dyb.jpg" alt="Thumbnail Image"
								class="img-circle img-responsive">
							<h5>Dong Yibo</h5>
						</div>
					</div>
					<div class="col-md-3">
						<div class="team-player">
							<img src="/Gitmining/images/gh.jpg" alt="Thumbnail Image"
								class="img-circle img-circle img-responsive">
							<h5>Gu Han</h5>
						</div>
					</div>
					<div class="col-md-3">
						<div class="team-player">
							<img src="/Gitmining/images/zsq.jpg" alt="Thumbnail Image"
								class="img-circle img-circle img-responsive">
							<h5>Zhang Shiqi</h5>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>